Repository watergis/maplibre-gl-export, pull requests merged in 2024-05, with the labels that each got.

#140 fix: add other necessary files to enable Portguese language
  .changeset/chatty-ghosts-repeat.md
  packages/mapbox-gl-export/README.md
  packages/maplibre-gl-export/README.md
  packages/maplibre-gl-export/src/lib/interfaces/Language.ts
  packages/maplibre-gl-export/src/lib/local/index.ts
Labels: bug

#141 Fix/add lang code
  .changeset/wicked-beds-invite.md
  packages/maplibre-gl-export/src/lib/interfaces/Language.ts
  packages/maplibre-gl-export/src/lib/interfaces/Translation.ts
  packages/maplibre-gl-export/src/lib/local/de.ts
  packages/maplibre-gl-export/src/lib/local/en.ts
  packages/maplibre-gl-export/src/lib/local/es.ts
  packages/maplibre-gl-export/src/lib/local/fi.ts
  packages/maplibre-gl-export/src/lib/local/fr.ts
  packages/maplibre-gl-export/src/lib/local/index.ts
  packages/maplibre-gl-export/src/lib/local/ja.ts
  packages/maplibre-gl-export/src/lib/local/pt.ts
  packages/maplibre-gl-export/src/lib/local/sv.ts
  packages/maplibre-gl-export/src/lib/local/uk.ts
  packages/maplibre-gl-export/src/lib/local/vi.ts
  packages/maplibre-gl-export/src/lib/local/zhHans.ts
  packages/maplibre-gl-export/src/lib/local/zhHant.ts
  sites/demo/src/routes/(demo)/+layout.svelte
  sites/demo/src/routes/(doc)/+page.svelte
  sites/demo/static/assets/mapbox-cdn-example.txt
  sites/demo/static/assets/maplibre-cdn-example.txt
Labels: documentation, enhancement

#142 Doc/add parameters doc
  README.md
  packages/mapbox-gl-export/README.md
  packages/mapbox-gl-export/demo.gif
  packages/maplibre-gl-export/README.md
  packages/maplibre-gl-export/demo.gif
  sites/demo/src/routes/(doc)/+page.svelte
  sites/demo/static/assets/mapbox-cdn-example.txt
  sites/demo/static/assets/maplibre-cdn-example.txt
Labels: documentation

#143 fix: use local language name for Translation object
  .changeset/afraid-bottles-jog.md
  packages/maplibre-gl-export/src/lib/local/de.ts
  packages/maplibre-gl-export/src/lib/local/es.ts
  packages/maplibre-gl-export/src/lib/local/fi.ts
  packages/maplibre-gl-export/src/lib/local/fr.ts
  packages/maplibre-gl-export/src/lib/local/ja.ts
  packages/maplibre-gl-export/src/lib/local/sv.ts
  packages/maplibre-gl-export/src/lib/local/uk.ts
  packages/maplibre-gl-export/src/lib/local/vi.ts
  packages/maplibre-gl-export/src/lib/local/zhHans.ts
  packages/maplibre-gl-export/src/lib/local/zhHant.ts
Labels: enhancement

#144 Contributing
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  packages/mapbox-gl-export/README.md
  packages/maplibre-gl-export/README.md
Labels: documentation

#146 feat: add attribution at the bottom-right of the exported image
  .changeset/cuddly-beers-flash.md
  packages/mapbox-gl-export/README.md
  packages/mapbox-gl-export/src/lib/export-control.ts
  packages/mapbox-gl-export/src/lib/map-generator.ts
  packages/maplibre-gl-export/README.md
  packages/maplibre-gl-export/index.ts
  packages/maplibre-gl-export/src/lib/export-control.ts
  packages/maplibre-gl-export/src/lib/interfaces/AttributionStyle.ts
  packages/maplibre-gl-export/src/lib/interfaces/ControlOptions.ts
  packages/maplibre-gl-export/src/lib/interfaces/index.ts
  packages/maplibre-gl-export/src/lib/map-generator-base.ts
  packages/maplibre-gl-export/src/lib/map-generator.ts
  sites/demo/src/routes/(doc)/+page.svelte
Labels: enhancement

#148 feat: add Catalan translation
  .changeset/two-peas-eat.md
  packages/maplibre-gl-export/src/lib/local/ca.ts
  packages/maplibre-gl-export/src/lib/local/index.ts
Labels: enhancement

#159 Update map-generator.ts to check for images data before calling addImage
  .changeset/chilly-colts-walk.md
  packages/mapbox-gl-export/src/lib/map-generator.ts
  packages/maplibre-gl-export/src/lib/map-generator.ts
Labels: bug

#160 fix: fixed docs layout for responsive
  sites/demo/src/routes/(doc)/+page.svelte
Labels: documentation

#163 feat: export north icon as a symbol layer
  .changeset/chilly-dolls-cheer.md
  packages/mapbox-gl-export/src/lib/export-control.ts
  packages/mapbox-gl-export/src/lib/map-generator.ts
  packages/maplibre-gl-export/index.ts
  packages/maplibre-gl-export/src/lib/export-control.ts
  packages/maplibre-gl-export/src/lib/interfaces/ControlOptions.ts
  packages/maplibre-gl-export/src/lib/map-generator-base.ts
  packages/maplibre-gl-export/src/lib/map-generator.ts
  sites/demo/src/routes/(doc)/+page.svelte
Labels: enhancement

#169 fix: add visibility and position option for attribution control.
  .changeset/weak-plums-suffer.md
  packages/mapbox-gl-export/src/lib/export-control.ts
  packages/mapbox-gl-export/src/lib/map-generator.ts
  packages/maplibre-gl-export/index.ts
  packages/maplibre-gl-export/src/lib/export-control.ts
  packages/maplibre-gl-export/src/lib/interfaces/AttributionStyle.ts
  packages/maplibre-gl-export/src/lib/interfaces/ControlOptions.ts
  packages/maplibre-gl-export/src/lib/map-generator-base.ts
  packages/maplibre-gl-export/src/lib/map-generator.ts
  sites/demo/src/routes/(doc)/+page.svelte
Labels: enhancement
